---
title: "p8105_hw2_yw4665"
author: "Yishi Wang"
date: "2025-09-23"
output: github_document
---

## Package calls
Call necessary libraries here:
```{r}
library(tidyverse)
```

## Problem 1
Read desired data from the local_files folder and assign them to according variables:
```{r}
pols_month_df = read_csv("local_files/fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names()
unemployment_df = read_csv("local_files/fivethirtyeight_datasets/unemployment.csv") |>
  janitor::clean_names()
snp_df = read_csv("local_files/fivethirtyeight_datasets/snp.csv") |>
  janitor::clean_names()
```
Clean the the pols_month dataframe first and assign the result df to 'cleaned_pols_month_df':
```{r}
cleaned_pols_month_df = pols_month_df |> 
  separate("mon", c("year", "month", "day"), "-") |> 
  mutate(
    month = month.name[as.integer(month)],
    president = if_else(prez_gop == 0, "dem", "gop")
    ) |>
  select(-prez_gop, -prez_dem, -day)
```

Now clean the snp dataframe with similar procedures:
```{r}
cleaned_snp_df = snp_df |>
  separate("date", c("month", "day", "year"), "/") |>
  mutate(
    month = month.name[as.integer(month)],
    year = if_else(as.integer(year) < 30, as.integer(year) + 2000, as.integer(year) + 1900 )
  ) |> 
  select(year, month, close)
```


